### PR TITLE
Westy remove guid

### PR DESCRIPTION
**Pull request by westyUMass**

### CODE REVIEW

**Comment by v-arun** [comment]
Are removes all cleaned up or is this just remove GUID but not other remove operations?

**Comment by westyUMass** [comment]
this is removeGuid and removeAccount. Which other removes need to be worked on?

**Comment by v-arun** [comment]
How have you stress-tested these? Can you write a simple test to create 100 sub-GUIDs (to keep the account record under [MAX_CHECKPOINT_SIZE](https://github.com/MobilityFirst/gigapaxos/blob/master/src/edu/umass/cs/gigapaxos/PaxosConfig.java#L303) remove them, and repeat this 10 times? This should mostly stress-test reconfigurators as they will go through at least couple checkpoints with the default checkpoint interval of 400. Reconfigurator checkpoints will likely trigger timeouts.

**Comment by v-arun** [comment]
I don’t know which other. Maybe none if RemoteQuery is no longer being used. Can we deprecate RemoteQuery?

**Comment by westyUMass** [comment]
Sure. Once you looked them over I was going to start working on parallelizing them. Figure that was an optimization so first I should get the basic framework functional before I started optimizing.

**Comment by v-arun** [comment]
Ok, can you add the stress-test above?

**Comment by westyUMass** [comment]
Did you see my question about RemoteQuery? We need a replacement for remoteQuery#deleteRecordSuppressExceptions. Didn't see anything obvious in the GNSClientInternal.

**Comment by westyUMass** [comment]
And yes, stress test.

**Comment by westyUMass** [comment]
ran this 10 times:

./scripts/loop "ant runtest -Dtest=RemoveGuidStressTest -DgigapaxosConfig=conf/gnsclient.1local.properties -Djava.util.logging.config.file=conf/logging.gns.client.debug.properties" 10

===================successes=10, failures=0==================

For each of the 3 remove types subguid, subguid with account, account guid it creates 100 guids and removes them.

**Comment by westyUMass** [comment]
Created a new merge request with the tests included. Close this one.

**Pull request closed without merging**
