### PR TITLE
Created GNSHttpProxy, a HTTP proxy for sending GNSCommands to a remote server.

### PR DESCRIPTION
**Pull request by bpteich**
This involved making the GNSHttpProxy class as a parent of GNSHttpServer. It has all of the functionality of GNSHttpServer except for the local request handling since it is intended to be used as a lightweight persistent client rather than a replica.

To run it first make sure you have re-jarred everything with:
ant jar

The following command starts the Proxy server:
java -cp ./jars/gns-cli-1.19.11.jar -DgigapaxosConfig=conf/gnsserver.3local.unittest.properties -Djavax.net.ssl.keyStorePassword=qwerty -Djavax.net.ssl.keyStore=conf/keyStore.jks -Djavax.net.ssl.trustStorePassword=qwerty -Djavax.net.ssl.trustStore=conf/trustStore.jks -ea edu.umass.cs.gnsserver.httpserver.GNSHttpProxy

Optionally -DgnsProxy.port=20080 and -DgnsProxy.remoteHostname=0.0.0.0 can be set if you wanted to listen on port 20080 and accept all incoming connections, etc.  By default port 8080 is used, and remoteHostname=localhost so that only local connections are accepted.

Then once it is running you can test it with:
ant runtest -Dtest="HttpProxyTest"
The test is identical to the existing HttpClientTest, but uses the default port of the GNSHttpProxy.
Right now the Proxy will accept commands from any http requests in receives, so it has no security if you do not have a firewall blocking 8080 requests coming in to where the proxy is hosted. I plan to update the Proxy to allow the port it is run on to be set at runtime, and to set what Net Addresses it accepts requests from. I think by default I will set it to only accept HTTP requests from the local host.

### CODE REVIEW

**Comment by bpteich** [comment]
Since normally I would review (1 mod 4), I requested review from Karthik as he's next in line.  Is that the correct protocol?

**Comment by westyUMass** [comment]
That's the protocol, but I've been violating it to get whoever is the least busy at the time (ie., not Arun :-) ) to review my changes.

**Comment by westyUMass** [comment]
For the test code can you have HttpProxyTest extend HttpClientTest, make the change in the constructor and avoid duplicating the code?

**Comment by bpteich** [comment]
I didn't know you could use inheritance with JUnit classes, but I just read it and that makes sense. I'll do that and a few other changes then resubmit.

**Comment by westyUMass** [comment]
Also, FYI you don't have to close the pull request. If you push new changes to the branch the pull request is updated. Unless you wanted to close it :-)

**Comment by bpteich** [comment]
Thanks for the heads up.

**Comment by westyUMass** [comment]
Why does it use gns-cli-1.19.11.jar? That's supposed to be just for the Command Line Interface (CLI). I think you just want the gnsserver-?.?.?.jar because the HTTP server is part of the server.

**Comment by bpteich** [comment]
I tried using the gnsserver jar originally, but then I had problems because java couldn't find the GNSClient class.  Using gns-cli seems to also include the HTTP server so I used that, but it might be better to explicitly include both in the classpath.

**Comment by westyUMass** [comment]
Probably better in that case to include server and client jars then. That seems to be what the gpServer script is doing.

**Comment by westyUMass** [comment]
At the risk of being pedantic, isn't there an opportunity for mode code sharing between the GNSHttpProxy and GNSHttpServer? In general this is a good idea and specifically in this case where the code is full of special cases and can be a bit opaque, having two copies of some of the methods seems like a bad idea. GNSHttpServer should inherit most of the code from GNSHttpProxy. The only part that's not in GNSHttpProxy is the local handling, right?

**Comment by bpteich** [comment]
Yeah, I moved a bunch from GNSHttpServer into GNSHttpProxy, but there are a few things that are a bit more complicated to move because of the nested classes.  I'm working on reducing the amount of duplicated code there as well, but it's taking me a little while to plan it out.  For example, to reduce the amount of duplicated code in the EchoHttpHandler I think I'll need to make the handle method in the parent class print most of the information, but have a method call to a method that provides extra information, and then have the child override this to add the few extra lines related to the request handler information, which I think is just the number of servers right now.

**Comment by westyUMass** [comment]
Yep... stuff like that is what I was expecting. Unless there's a compelling need to get this into the master branch immediately shall we wait for your commits before merging?

**Comment by westyUMass** [comment]
I'm confused was to why this looks like it has a lot of commits that look identical to what is already in the master branch.

**Comment by bpteich** [comment]
That commit was just merging in changes from the main branch. I had to manually resolve differences in GNSHttpServer, all of the other files should be identical to the master branch.

**Comment by westyUMass** [comment]
I notice that GNSHttpProxy.java and GNSHttpServer.java are identical. What's the plan these files?

**Comment by bpteich** [comment]
The main difference between GNSHttpProxy and GNSHttpServer is that the proxy never executes and commands locally since it is intended to be used as a standalone client.  An example use case would be having a GNSHttpProxy running on a Clearpass Authentication machine that is setup to only accept HTTP commands from localhost.  Whenever the Clearpass server receives a user login event it sends an HTTP request to its local GNSHttpProxy to update a field in the user's GNS entry with their current location.  This would solve the problem of having to spawn a new jvm every time an asynchronous event happens that requires a GNS read or write, but still gives the benefits of a distributed system since GNSHttpProxy uses a GNSClient.

I'm trying to extract as much as I can from GNSHttpServer into GNSHttpProxy as its parent and leave only the necessary logic for handling local requests, but I'm doing it incrementally and making sure the GNSHttpServer still passes its tests after each refactoring.

**Comment by westyUMass** [comment]
Cool. Thanks for detailed response. Are you looking for an immediate merge on this pull request then? I'm assuming you are.

**Comment by bpteich** [comment]
I plan to finish refactoring by the middle of next week, so I think it would be fine to wait until then to merge this.

**Comment by westyUMass** [comment]
Allright. I'll hold off on the merge (and also try to not touch code that will create more conflicts for you :-))

**Comment by v-arun** [comment]
Closing this because of lack of recent activity and failing tests.

**Pull request closed without merging**
