### PR TITLE
The most recent changes to activecode package

### PR DESCRIPTION
**Pull request by zhaoyu2ndaccount**
This pull request has the following changes to activecode package:
1. Resolve the bug in [MOB-1095](https://mobileinternet.atlassian.net/browse/MOB-1095): update operation on an internal field should not trigger active code. The fix is between line 189-196 in [ActiveCodeHandler](https://github.com/zhaoyu2ndaccount/GNS/commit/a79431b916ba2f8d16793f568a76d6035f29fe97#diff-ffd9455dd04294dac3cdfb03c584111d)
2. Add GeoIP functionality into activecode: [GeoIpUtils](https://github.com/zhaoyu2ndaccount/GNS/commit/a79431b916ba2f8d16793f568a76d6035f29fe97#diff-3086bd577ece3e0e06ab65a8db07fe73)
3. Add a script engine to run trusted code: [TrustedRunner](https://github.com/zhaoyu2ndaccount/GNS/commit/a79431b916ba2f8d16793f568a76d6035f29fe97#diff-126505224b305c0b1c74b87e57b04d09). A code trusted by GNS does not need to be sent to a worker to run. This is just a minor optimization to the system performance. 
4. Resolve bugs in [ActiveMessage](https://github.com/zhaoyu2ndaccount/GNS/commit/a79431b916ba2f8d16793f568a76d6035f29fe97#diff-b9971a808a26a4bce05116e71872e885) and [ActiveQueryHandler](https://github.com/zhaoyu2ndaccount/GNS/commit/a79431b916ba2f8d16793f568a76d6035f29fe97#diff-00dc0ba45f22229d332f02cad67d4567) for remote write. 
5.  Clean up the code, e.g., remove dead code in ActiveMessage, update document in ActiveException.

### CODE REVIEW

**Comment by westyUMass** [comment]
There is a typo in ActiveCodeConfig.acitveCodeBlockingEnabled

A couple of questions about handleActiveCode method:

1) For a write if value contains any internal fields we don't write?

2) When you add the SOURCE_IP_FIELD to the value isn't there the possibility that the user has a field of the same name that will be overwritten?

**Comment by westyUMass** [comment]
Also, can you add a sentence or two to all of your public classes describing what they are and how they fit into the overall design.

**Comment by ZhaoyuUmass** [comment]
Thanks, I've fixed the typo.
To answer your questions:
1. For a write if value contains any internal fields, we won't trigger active code, the write operation won't be affected, as the original value will still be written into the internal fields(only active code won't be triggered). The reason is that we have no control over user's active code, and user has no privilege to write values into internal fields, therefore, we can't let active code to write into internal fields.
2. Yes, it is possible. It is used in the managed DNS service now, and I'll check whether header.getSourceAddress() != null, so it won't affect the users who do not use managed DNS service. Here is the doc of managed DNS service on this: [http://activegns.org/doc/activequery](http://activegns.org/doc/activequery), and hopefully they will pay attention to the notice so that they won't make the mistake.

**Comment by westyUMass** [comment]
Thanks for the doc for DNS. That makes sense to me.

For #1 (not writing internal fields) - I understand the purpose. But I'm wondering if there would be a way to just pull the internal fields from the value before passing it to the active code and then adding them back before actually writing the value.

However, that approach seems complicate and  maybe unnecessary I suspect. 

The current method seems to assume that if their are internal fields then the user (who maybe isn't a user and is in fact some internal system use) will not be expecting active code to operate on this write. I suppose that might be sufficient and not warrant a more complicated approach.

**Comment by westyUMass** [comment]
One last minor question: Do you think there is a way to allow for more modular additions of interfaces like the one you added for getLocations? Ie., some way that doesn't require adding methods to ActiveBlockingQuerier, but instead could be done by defining a new interface method and then calling something like (for lack of a better name) AddTheMethodToQuerier.

**Comment by ZhaoyuUmass** [comment]
Westy, I've updated the document for all public classes.
I'm not aware of a way to implement this "AddTheMethodToQuerier" function, but it sounds like a good idea.

**Pull request merged**
