### PR TITLE
Westy remove guid

### PR DESCRIPTION
**Pull request by westyUMass**
Same as before (new versions of removeGuid), but includes the test code

### CODE REVIEW

**Comment by westyUMass** [comment]
I need this merged into master to start working on the new version which will remove last RemoteQuery use. Also will attempt to parallelize. As I noted in the previous pull request the stress test passed 100 guids x 3 different tests x 10 loops

**Comment by v-arun** [comment]
I see that I merged this but it shows up as having failed the test. I also got an email saying build #659 failed. But it showed me as all checks passing while prompting the merge. Any idea what happened here?

**Comment by westyUMass** [comment]
#659 is still running from what I can see...

**Comment by v-arun** [comment]
That’s only because I restarted it just now.

**Pull request merged**
