### PR TITLE
Westy

### PR DESCRIPTION
**Pull request by westyUMass**
Removed a bunch of warnings

### CODE REVIEW

**Comment by v-arun** [comment]
Can you make a JIRA task for yourself to fix the failing select test along with the text logs from the failure?

**Comment by westyUMass** [comment]
What is the fix for a timeout when executing a guidCreate? Is there a pattern for this that already exists?

**Comment by v-arun** [comment]
No pattern. There is already retransmission support for blocking GNSClient calls upon a timeout. ServerIntegrationTest already sets that to 1 retransmission using setNumRetriesUponTimeout. There should be no reason to need more than one retransmission in a single-machine test, but you can increase it if it helps.

If the failure is because a CreateServiceName fails midway at reconfigurators, retransmitting the create won’t help it succeed. If you find a create timing out, send me FINEST logs for such a run.

**Comment by westyUMass** [comment]
https://mobileinternet.atlassian.net/browse/MOB-1077

**Comment by v-arun** [comment]
Since I see 4 out of 5 failures above and the master head's failure rate is much lower, I'll close this pull request.

**Comment by westyUMass** [comment]
This was just a bunch of warning fixes.

**Comment by v-arun** [comment]
I understand. But we can not merge a failing branch, so I don’t know what else to do.

**Pull request closed without merging**
