### PR TITLE
Travis CI status checks for GNS

### PR DESCRIPTION
**Pull request by akarthik10**
This change introduces a script for doing status checks on Travis CI. The status check will ensure that the number of javac/javadoc warnings and errors will never increase.

### CODE REVIEW

**Comment by akarthik10** [comment]
I see that there have been other commits after this pull request has been raised. They could have changed the warning counts. I'll have to resubmit this request again, but I'll hold to see if there are any comments on this.

**Comment by v-arun** [comment]
Are you checking for all the things in the standards document? Are you checking for unused variables or methods? Dead code?

**Comment by akarthik10** [comment]
No, I learnt that javac does not support unused variable/method detection. This is something that is provided by eclipse in its own compiler. If we want unused variable/method detection, we'll have to use a third party tool that does that.

**Comment by akarthik10** [comment]
And, Eclipse compiler can used instead that does these checks. It is available as an open source tool.

**Comment by v-arun** [comment]
Can you add the eclipse compiler to our travis checks?

**Comment by akarthik10** [comment]
OK, I'll do that. Should I replace these `javac` checks with Eclipse checks, or add that check additionally?

**Comment by v-arun** [comment]
I don’t know on what basis to answer, so you make that call.

**Comment by akarthik10** [comment]
Closing this pull request. Will submit a new one with eclipse checks.

**Comment by westyUMass** [comment]
Was this meant for me to merge? Sorry, if it was. We don't get a lot of pull requests.

**Comment by v-arun** [comment]
Westy, not necessarily, just hold off on commits. Submit pull requests from now on.

**Pull request closed without merging**
