### PR TITLE
Remove dependency on javax.xml.DatatypeConverter

### PR DESCRIPTION
**Pull request by kanantharamu**
This change is to make j2objc work with GNSClient, as j2objc doesn't support `javax.xml.*` yet

### CODE REVIEW

**Comment by westyUMass** [comment]
I can't get behind this change.  I get that you're trying to cut down on library dependencies, but this is directly at odds with code reuse and not writing new code that already had proven versions in libraries.

Also, hexStringToByteArray exhibits bugs when dealing with certain unicode multi byte strings which is why I removed uses of it from the system in the first place.

Bottom line is why write your own version when there is a proven library out that that lots of folks use.

**Comment by kanantharamu** [comment]
Please see my update on the other pull request. If you think doing this is bad, maybe I'll have to do more planning before raising any more pull requests.

**Comment by westyUMass** [comment]
Yeah... this one say no. That old code is buggy. If you can find another lib that is easier to deal with...

**Comment by kanantharamu** [comment]
I'll see if I can translate the actual dependency.

**Comment by kanantharamu** [comment]
I was able to translate `javax.xml.bind.DatatypeConverter' (and its transitive dependencies) using j2objc. I haven't tested it but the translation was successful. I'll close this PR as we now have an alternative.

**Comment by westyUMass** [comment]
Awesome. Good to know.

**Pull request closed without merging**
