### PR TITLE
Clean up GNS ACL check

### PR DESCRIPTION
**Pull request by ZhaoyuUmass**
The ACL check in the current GNS implementation is not efficient. The main reason that causes the inefficiency is that it calls the method NSFieldMetaData.lookupLocally which involves many unnecessary operations to fetch meta data of a target GUID. For the method like unsigned read, it even involves multiple calls of this method. Here is the path for unsigned read ACL check:
NSAuthentication.signatureAndACLCheck -> 
// If no signature, then just check whether the field is accessible by everyone
NSAccessSupport.fieldAccessibleByEveryone -> NSFieldMetaData.lookupLocally -> NSFieldAccess.lookupListFieldLocallyNoAuth -> NameRecord.getNameRecordMultiUserFields -> BasicRecordMap(GNSRecordMap).lookupUserFields -> NoSqlRecords.lookupSomeFields -> DiskMapRecord.lookupSomeFields -> DiskMapRecord.lookupEntireRecord

Another example is the method NSAuthentication.aclCheck which will also call the NSFieldMetaData.lookupLocally:
NSAuthentication.aclCheck -> NSAuthentication.lookupPublicKeyInACL -> NSAccessSupport.lookupPublicKeysFromAcl -> NSFieldMetaData.lookupLocally -> NSFieldAccess.lookupListFieldLocallyNoAuth -> NameRecord.getNameRecordMultiUserFields -> BasicRecordMap(GNSRecordMap).lookupUserFields -> NoSqlRecords.lookupSomeFields -> DiskMapRecord.lookupSomeFields -> DiskMapRecord.lookupEntireRecord

Since these two methods will both call DiskMapRecord.lookupEntireRecord to get the entire record of a target GUID, therefore, we could call DiskMapRecord.lookupEntireRecord to fetch the entire record, and if we need to get the entire record for ACL check for a same request, we do not need to fetch it again. Instead, we could reuse the value already fetched from the database.

Therefore, the new implementation takes short path to fetch the entire record:
NSAuthentication.signatureAndACLCheck -> GNSRecordMap.lookupEntireRecord -> NoSqlRecords.lookupEntireRecord -> DiskMapRecord.lookupEntireRecord

This pull request has the following changes to the master branch:
1. Re-implement ACL check for both read and write command in GNS, the changes are made to the following classes: 
[src/edu/umass/cs/gnscommon/GNSProtocol.java](https://github.com/MobilityFirst/GNS/compare/master...zhaoyu2ndaccount:master#diff-a1bd88ed7ee96b6aa5201f15189b7007): add two constants which used to be hard-coded in the code, 
[src/edu/umass/cs/gnscommon/SharedGuidUtils.java](https://github.com/MobilityFirst/GNS/compare/master...zhaoyu2ndaccount:master#diff-cb410060e7444168b7fd10b651f60ba7): add a method to retrieve public key from a JSONArray whitelist,
[src/edu/umass/cs/gnsserver/gnsapp/clientSupport/NSAccessSupport.java](https://github.com/MobilityFirst/GNS/compare/master...zhaoyu2ndaccount:master#diff-fbdfd57fe39ffbb9992692d25156675f): add a method to check whether there exists an item in a JSONArray, re-implement the method fieldAccessibleByEveryone, add a method called getMataDataForACLCheck to fetch the meta data from the database, re-implement the method lookupPublicKeysFromAcl to reuse the fetch meta data without accessing database again, clean up warnings,
[src/edu/umass/cs/gnsserver/gnsapp/clientSupport/NSAuthentication.java](https://github.com/MobilityFirst/GNS/compare/master...zhaoyu2ndaccount:master#diff-6178dd04be921a82984ca62b4d5bb65d): re-implement aclCheck and lookupPublicKeyInACL methods, clean up warnings

2. Update document for ACL check in [edu.umass.cs.gnsclient.client.singletests.AclDefaultTest](), refine test case test_158_ACLReadDeeperFieldOtherFail, which should succeed instead of fail.

3. Update [src/edu/umass/cs/gnsclient/client/testing/GNSClientCapacityTest.java](https://github.com/MobilityFirst/GNS/compare/master...zhaoyu2ndaccount:master#diff-a8c9b6fc84ac84772caf6e026b265bc6) test: resolve a bug in the test which makes the client as the bottleneck for throughput test, add different operation test cases (including, write, write with ACL, read with ACL, remove). The write and read with ACL tests are used to show the improvement after reimplementing ACL check method. Write and read with ACL test cases use an accessor GUID to write/read a field of a target GUID, where accessor is different from target GUID.

The test is done with a single server(t2.medium) and single client (c4.xlarge) in a same LAN on EC2. 
Here is the performance comparison(average across 10 runs):
parallel write: 					4K/s			4K/s
parallel write with ACL: 			4K/s			4.7K/s
parallel signed read: 			20.5K/s			21K/s
parallel unsigned read:			17.9K/s			34K/s
parallel signed read with ACL: 	11.3K/s			18K/s
parallel remove: 				4.9K/s			5K/s

### CODE REVIEW

**Comment by westyUMass** [comment]
RE the "two constants which used to be hard-coded in the code" see
edu.umass.cs.gnsserver.gnsapp.recordmap.NameRecord#VALUES_MAP
and also 
edu.umass.cs.gnsserver.gnsapp.clientCommandProcessor.commandSupport.FieldMetaData

**Comment by westyUMass** [comment]
I think you're missing one ACL case (unless you're changing the way ACLs work (again)). When a deeper layers ACL is EMPTY that implies no-one other than the GUID itself can access that level or below. That test case you changed was testing for this. This was a change we made a few months back so unless your changing it back...

**Comment by ZhaoyuUmass** [comment]
Westy, thanks for the explanation, now I understand why that test case is needed. I'll fix the test.
This value "nr_valuesMap" in edu.umass.cs.gnsserver.gnsapp.recordmap.NameRecord#VALUES_MAP is not a string, and I'd like to use it as a string, that's the reason I created a String constant in GNSProtocol. Actually, we could substitute this "nr_valuesMap" value in edu.umass.cs.gnsserver.gnsapp.recordmap.NameRecord#VALUES_MAP with GNSProtocol.META_DATA_FIELD("nr_valuesMap").  
The method edu.umass.cs.gnsserver.gnsapp.clientCommandProcessor.commandSupport.FieldMetaData#makeFieldMetaDataKey does give me a correct path to the field in a dotted format. But to get the correct path to the field from it,  I have to split it again, which seems unnecessary. That's the reason I add a constant MD in GNSProtocol to represent the field "md".

**Comment by ZhaoyuUmass** [comment]
I've reverted the ACL test, test.edu.umass.cs.gnsclient.client.singletests.AclDefaultTest, and all tests passed with the changes in this pull request.
The performance improved as shown above.

**Pull request merged**
