### PR TITLE
Westy select fix

### PR DESCRIPTION
**Pull request by westyUMass**
GNSApp now picks an address "safely" for the node (was breaking on EC2 NAT).

### CODE REVIEW

**Comment by v-arun** [comment]
The Getting Started page on github works fine with EC2 and I am not aware of any NAT issues. Can you explain more why this fix is needed, e.g., by saying what address it should be and what it ends up being? Looking at the red/green diffs, the red stuff looks right to me and your fix in green seems potentially wrong to me.

If you use public IP addresses or DNS names, there should be no problem. You should not be using anything else in properties files.

The last I checked, getBindAddress was unnecessary and should be deprecated.

**Comment by westyUMass** [comment]
The address being returned by messenger.getListeningSocketAddress() was the ipv6 unspecified address 0:0:0:0:0:0:0:0:24303

2017-02-13 16:13:08 [INFO] === Node frank_Repl listening on /0:0:0:0:0:0:0:0:24303===

**Comment by westyUMass** [comment]
This is in the config file:

active.frank_Repl=52.0.29.143:24303

reconfigurator.frank_Recon=52.0.29.143:24304

That's an EC2 static ip.

**Comment by v-arun** [comment]
Ok, here is what is happening: nio can not bind to the public 52.0.29.143 address, so it falls back to the wildcard address. The fix is to use the nodeConfig address but it suffices to use the address in the properties file; getBindAddress is unnecessary or, equivalently, it should be okay to have getBindAddress return just the default address.

The clean way here is to use messenger.getNodeConfig(), not for GNSApp to construct it itself, and just use getNodeAddress.

**Comment by westyUMass** [comment]
Cool. I'm going to clean up the nodeConfig code in GNSApp.

**Pull request closed without merging**
