### PR TITLE
Remove dependency on msgpack and jackson

### PR DESCRIPTION
**Pull request by kanantharamu**
This change removes msgpack and jackson from `JSONByteConverter`

### CODE REVIEW

**Comment by westyUMass** [comment]
This code was written as way to facilitate a comparison various methods of encoding packets. Are you sure you're not removing functionality that we might use someday?

**Comment by kanantharamu** [comment]
In last week's meeting, it was decided to remove these. I've also added
@v-arun as a reviewer to take a second look at this. Merging this can wait
until he approves.

**Comment by westyUMass** [comment]
OK... that's what I was wondering. Thanks.

**Comment by v-arun** [comment]
Removing msgpack and jackson and tests that depend on them is fine by me.

**Pull request merged**
